---
- name: VAGRANT | fetch checksum
  become: true
  get_url:
    url: "{{ vagrant_deb_sha_url }}"
    dest: /tmp/vagrant-checksum

- name: VAGRANT | filter checksum
  become: true
  shell: "cat /tmp/vagrant-checksum | grep x86_64.deb | cut -d' ' -f1"
  register: vagrant_sha

- name: VAGRANT | download vagrant deb
  become: true
  get_url:
    url: "{{ vagrant_deb_url }}"
    dest: /opt/vagrant.deb
    checksum: "sha256:{{ vagrant_sha.stdout }}"

- name: VAGRANT | Install vagrant
  become: true
  apt:
    deb: "/opt/vagrant.deb"

- name: VAGRANT | remove files
  become: true
  file:
    state: absent
    path: "{{ item }}"
  with_items:
    - /opt/vagrant.deb
    - /tmp/vagrant-checksum

- name: List installed Vagrant plugins
  become: True
  shell: "vagrant plugin list -c 'vagrant plugin list'"
  changed_when: False
  register: vagrant_initial_plugins_list
  tags:
    - vagrant
    - install

- name: Install Vagrant plugins
  become: True
  shell: "vagrant plugin install -c 'vagrant plugin install {{ item.name }}'"
  with_items: "{{ vagrant_plugins }}"
  when:
    - "{{ item.state == 'present' }}"
    - "{{ item.name not in vagrant_initial_plugins_list.stdout }}"
  tags:
    - vagrant
    - install

- name: Uninstall Vagrant plugins
  become: True
  shell: "su - {{ vagrant_plugins_user }} -c 'vagrant plugin uninstall {{ item.name }}'"
  with_items: "{{ vagrant_plugins }}"
  when:
    - "{{ vagrant_plugins_user != '' }}"
    - "{{ item.state == 'absent' }}"
    - "{{ item.name in vagrant_initial_plugins_list.stdout }}"
  tags:
    - vagrant
    - install

