---
- name: VIRTUALBOX | add vb secure key
  become: true
  apt_key:
    url: "{{ virtualbox_apt_key_url }}"
    state: present
  when: ( ansible_distribution == 'Debian' and ansible_distribution_version >= '8' ) or
        ( ansible_distribution == 'Ubuntu' and ansible_distribution_version >= '16.04' )

- name: VIRTUALBOX | add vb secure key (old)
  become: true
  apt_key:
    url: "{{ virtualbox_apt_key_url_old }}"
    state: present
  when: ( ansible_distribution == 'Debian' and ansible_distribution_version < '8' ) or
        ( ansible_distribution == 'Ubuntu' and ansible_distribution_version < '16.04' )

- name: VIRTUALBOX | add paket sources
  become: true
  apt_repository:
    repo: "deb http://download.virtualbox.org/virtualbox/debian {{ ansible_distribution_release }} contrib"
    state: present

- name: VIRTUALBOX | install virtualbox
  become: true
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - "linux-headers-{{ ansible_kernel }}"
    - dkms
    - build-essential
    - "virtualbox-{{ virtualbox_version }}"

- name: Check if extension pack is already installed
  shell: "VBoxManage list extpacks"
  register: extpack_list

- name: Output installed extpacks
  debug:
    var: download_result.stdtout

- name: Download VirtualBox extension pack
  get_url:
    url: "{{ virtualbox_repo_base_url }}/{{ virtualbox_extpack_version }}/Oracle_VM_VirtualBox_Extension_Pack-{{ virtualbox_extpack_version }}.vbox-extpack"
    dest: /tmp/
    force: yes
  register: download_result
  when: 'extpack_list.stdout == "Extension Packs: 0"'

- name: Output downloaded VirtualBox extension pack file name
  debug:
    var: download_result.dest
    verbosity: 1

- name: Install VirtualBox extension pack
  shell: "echo 'y' | VBoxManage extpack install --replace {{ download_result.dest }}"
  when: 'extpack_list.stdout == "Extension Packs: 0"'

- name: VIRTUALBOX | add users to vb-group
  become: true
  user:
    name: "{{ item }}"
    groups: vboxusers
    append: yes
  with_items: "{{ virtualbox_users }}"
